/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author turtl
 */

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.Random;
import java.io.InputStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import java.util.concurrent.TimeUnit; 


public class GameWindow extends javax.swing.JFrame {

    static int finalescore; //int to go across classes

    /**
     * Creates new form GameWindowOne
     */
    
    String answer;
    int p ;
    int score;
    int strikes;
    public String[] questions = {"Bathroom", "Kitchen", "Bedroom", "Car"};
    //array for each question 
    String question;
    int questionNumber;
    public static int finaleScore;
    File QA = new File(""); 
    boolean b;
    
    public GameWindow() {
        initComponents();
        score = 0;
        strikes = 0;
        question = "";
        questionNumber = 0;
        b = false;
        //constructor to set values to 0 to start -- bc of possible play again loop
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        answerTwo = new javax.swing.JLabel();
        answerOne = new javax.swing.JLabel();
        answerFour = new javax.swing.JLabel();
        answerFive = new javax.swing.JLabel();
        answerThree = new javax.swing.JLabel();
        answerInput = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        labelScore = new javax.swing.JLabel();
        scorenumberlabel = new javax.swing.JLabel();
        strikelabel = new javax.swing.JLabel();
        numStrikes = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 225, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        questionLabel.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        questionLabel.setFocusable(false);
        questionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        answerTwo.setBackground(new java.awt.Color(1, 1, 1));
        answerTwo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        answerTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerTwo.setText("2");
        answerTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        answerOne.setBackground(new java.awt.Color(1, 1, 1));
        answerOne.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        answerOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerOne.setText("1");
        answerOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        answerFour.setBackground(new java.awt.Color(1, 1, 1));
        answerFour.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        answerFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerFour.setText("4");
        answerFour.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        answerFive.setBackground(new java.awt.Color(1, 1, 1));
        answerFive.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        answerFive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerFive.setText("5");
        answerFive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        answerThree.setBackground(new java.awt.Color(1, 1, 1));
        answerThree.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        answerThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerThree.setText("3");
        answerThree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        answerInput.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        answerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerInputActionPerformed(evt);
            }
        });

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        labelScore.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelScore.setText("Score:");

        scorenumberlabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        scorenumberlabel.setText("0");

        strikelabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        strikelabel.setText("Strikes");

        numStrikes.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        numStrikes.setText("_ _ _");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scorenumberlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(strikelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(numStrikes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(answerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerThree, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerOne, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerFour, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerFive, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(answerOne, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(answerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(answerThree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(answerFour, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(answerFive, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strikelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numStrikes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scorenumberlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(quitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0); //close program
    }//GEN-LAST:event_quitButtonActionPerformed

    private void answerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerInputActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        //String answer;
        answer = answerInput.getText(); //get input
        boolean c;
        c = searching(); //figures out if input is correct
        System.out.println(c);
        if (c){
            outputCorrectAnswer(); 
        }
        else{
            incorrectAnswer();
        }
        
        
    }//GEN-LAST:event_enterButtonActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        
    }//GEN-LAST:event_jPanel1FocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        questionChoice();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
        
    }
    
    public void questionChoice(){
        Random randomNum = new Random();
        questionNumber = randomNum.nextInt(4); //choose random number between 0-3
        System.out.println(questionNumber);
        question = questions[questionNumber];
        System.out.println(question); //prints for checking program works - for testing
        switch (questionNumber){
            case 0: //sets questions based off randomized number
                questionLabel.setText("Things found in the Bathroom"); 
                break;
            case 1:
                questionLabel.setText("Things found in the Kitchen");
                break;
            case 2:
                questionLabel.setText("Things found in the Bedroom");
                break;
            case 3:
                questionLabel.setText("Things found in the Car");
                break;
        }
    }
    public boolean searching(){
       boolean a = false;
       switch (questionNumber){ //depending on question it needs to open a dif answer file
           case 0: 
               QA = new File ("Q1Ainfo.txt");
               break;
           case 1:
               QA = new File ("Q2Ainfo.txt");
               break;
           case 2:
               QA = new File ("Q3Ainfo.txt");
               break;
           case 3:
               QA = new File ("Q4Ainfo.txt");
               break;
       }
       p = 0;
       try{
           Scanner reading = new Scanner(QA);
           while(!a){
               String line = reading.nextLine();//read each line of file one at a time
               System.out.println(line);
               p++; //keeps track of line number
               System.out.println(p);
               a = line.equalsIgnoreCase(answer); //check if input matches ignoring case 
               System.out.println(answer);
               System.out.println(a);
               System.out.println(""); //prints for testing
               if (p>=5){
                   return a; // if gets to end of file w/out true return false
               }
               else{
                   continue;
               }
           }
           return a; // a is whether input is t/f a correct answer
       }
       catch (FileNotFoundException e){ //catch if it can't find the file
           System.out.println("File not found");
       }
       return false; 
    }
    
    public void incorrectAnswer(){
        answerInput.setText(""); //clears input field
        strikes++; //keeps track of strikes
        switch(strikes){ //outputs amount of strikes depending on above var
            case 1:
                numStrikes.setText("X _ _");
                break;
            case 2:
                numStrikes.setText("X X _");
                break;
            case 3:
                numStrikes.setText("X X X");
                
        }
        InputStream incorrectMusic;
        try{
            incorrectMusic = new FileInputStream(new File("07042294.wav")); //make object of file
            AudioStream playsound = new AudioStream(incorrectMusic);
            AudioPlayer.player.start(playsound); //play audio file
        }
        catch (IOException e){ //catches error
            System.out.println("IO Exception");
        }
        if (strikes == 3){ //if get three strikes go to end method
            endGame();
        }
    }
    
    public void outputCorrectAnswer(){
        answerInput.setText(""); //clears input field
        System.out.println("");
        String getAnswerText = ""; //sets empty string
       try{
        Scanner read = new Scanner(QA);
        for (int i = 1; i<=5; i++){ //for the amount of lines
            getAnswerText = read.nextLine(); //read answer
            System.out.println(getAnswerText);
            if (p == i){ // if the line number for the correct answer is the same number as the read line
                switch (p){//set text to the read line
                    case 1:
                        answerOne.setText(getAnswerText);
                        score += 100;
                        break;
                    case 2:
                        answerTwo.setText(getAnswerText);
                        score += 200;
                        break;
                    case 3:
                        answerThree.setText(getAnswerText);
                        score += 300;
                        break;
                    case 4:
                        answerFour.setText(getAnswerText);
                        score += 400;
                        break;
                    case 5:
                        answerFive.setText(getAnswerText);
                        score += 500; //adds score for each answer
                        break;
                    
            }
        }
            else {
                continue;
            }
       }
       }
       catch (FileNotFoundException e){ //catch if can't find file
           System.out.println(e);
       }
       
       InputStream music;
       try{
           GameWindow f = new GameWindow();
           music = new FileInputStream(new File ("07037425.wav")); //create object for audio file
           AudioStream play = new AudioStream(music);
           AudioPlayer.player.start(play); //start audio
           TimeUnit.SECONDS.sleep(3); //file longer than needed so timeunit plays for three secs
           AudioPlayer.player.stop(play); //stops audio
       }
       catch (IOException e){ 
           System.out.println("IO Exception");
       }
       catch (InterruptedException e){ //catch issue with timeunit
           System.out.println("Interrupted Exception");
       }
       
       scorenumberlabel.setText(String.valueOf(score));
            if (score >= 1500){ //if score is the total possible amount send to end method
                endGame();
            }
    }
    
    public void endGame(){
        finalescore = score; //sets score to static var
        this.dispose();
        EndWindow endingPage = new EndWindow(); //create object and open new window
        endingPage.setVisible(true);
    }  
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerFive;
    private javax.swing.JLabel answerFour;
    private javax.swing.JTextField answerInput;
    private javax.swing.JLabel answerOne;
    private javax.swing.JLabel answerThree;
    private javax.swing.JLabel answerTwo;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelScore;
    private javax.swing.JLabel numStrikes;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel scorenumberlabel;
    private javax.swing.JLabel strikelabel;
    // End of variables declaration//GEN-END:variables
}
